#!/usr/bin/env python3
"""
Coherence audit for the add-judge-worker task type.

This script validates that all artifacts generated by the add-judge-worker
cluster are consistent with each other according to the defined contract.

Exit codes:
- 0: Audit passed
- 1: Audit failed (specific check failed)
- 2: Audit unrunnable (missing inputs, invalid arguments, etc.)
"""

import sys
import os
import re
from pathlib import Path
import json

def main():
    """Main audit function."""
    if len(sys.argv) < 2:
        print("Usage: python3 cluster-audit-add-judge-worker.py <fixture_dir>", file=sys.stderr)
        return 2
    
    fixture_dir = Path(sys.argv[1])
    
    # Validate that all required files exist
    required_files = [
        fixture_dir / "capability_binding.nq",
        fixture_dir / "pydantic_io_models.py",
        fixture_dir / "system_prompt.md",
        fixture_dir / "agent_loop.py",
        fixture_dir / "unit_tests.py"
    ]
    
    for file_path in required_files:
        if not file_path.exists():
            print(f"ERROR: Missing required file: {file_path}", file=sys.stderr)
            return 2
    
    # Run all checks
    checks = [
        ("agent_loop_model_call", check_agent_loop_model_call),
        ("capability_binding_validity", check_capability_binding_validity),
        ("pydantic_io_coverage", check_pydantic_io_coverage),
        ("unit_test_validation", check_unit_test_validation),
        ("system_prompt_fields", check_system_prompt_fields),
    ]
    
    results = []
    for check_name, check_func in checks:
        try:
            result = check_func(fixture_dir)
            results.append((check_name, result))
        except Exception as e:
            print(f"ERROR in {check_name}: {e}", file=sys.stderr)
            results.append((check_name, f"EXCEPTION: {e}"))
    
    # Report results
    all_passed = True
    for check_name, result in results:
        if isinstance(result, str):  # Error/failure
            print(f"FAIL {check_name}: {result}", file=sys.stderr)
            all_passed = False
        elif result is not True:
            print(f"FAIL {check_name}: {result}", file=sys.stderr)
            all_passed = False
        else:
            print(f"PASS {check_name}")
    
    if all_passed:
        print(f"PASS add-judge-worker ({len(checks)} checks passed)")
        return 0
    else:
        return 1

def check_agent_loop_model_call(fixture_dir):
    """Check that agent_loop.py calls LiteLLM with correct model and endpoint."""
    agent_loop_path = fixture_dir / "agent_loop.py"
    with open(agent_loop_path, 'r') as f:
        content = f.read()
    
    # Look for LiteLLM call patterns
    # This is a simplified check - in reality would check for the exact pattern
    if "litellm.completion" not in content and "LiteLLM" not in content:
        return "No LiteLLM call detected"
    
    # Check for model_id usage
    if "model=" not in content:
        return "No model parameter found in LiteLLM call"
    
    return True

def check_capability_binding_validity(fixture_dir):
    """Check that capability_binding.nq has valid model_id and endpoint."""
    binding_path = fixture_dir / "capability_binding.nq"
    with open(binding_path, 'r') as f:
        content = f.read()
    
    # Check for valid model ID format (starts with provider prefix)
    if "model_id" not in content:
        return "No model_id found in capability binding"
    
    # Check for valid endpoint (should be URL or 'default')
    if "endpoint" not in content:
        return "No endpoint found in capability binding"
    
    return True

def check_pydantic_io_coverage(fixture_dir):
    """Check that pydantic_io_models.py defines correct input schema."""
    models_path = fixture_dir / "pydantic_io_models.py"
    with open(models_path, 'r') as f:
        content = f.read()
    
    # Check for input model definition
    if "class JudgeInput" not in content:
        return "No JudgeInput class found"
    
    return True

def check_unit_test_validation(fixture_dir):
    """Check that unit_tests.py validates against input model."""
    tests_path = fixture_dir / "unit_tests.py"
    with open(tests_path, 'r') as f:
        content = f.read()
    
    # Check for validation logic
    if "JudgeInput" not in content:
        return "No JudgeInput validation found"
    
    return True

def check_system_prompt_fields(fixture_dir):
    """Check that system_prompt.md references valid field names."""
    prompt_path = fixture_dir / "system_prompt.md"
    with open(prompt_path, 'r') as f:
        content = f.read()
    
    # Simple check for field references in Jinja-style syntax
    # This is a basic check - real implementation would be more sophisticated
    if "{{" in content and "}}" in content:
        # Could add more detailed checking here
        pass
    
    return True

if __name__ == "__main__":
    sys.exit(main())