//! Read-only session inspection over the persisted orchestration store.
//!
//! Powers `dec session list` and `dec session log` (FT-012).
//!
//! These commands materialise the read-side of FT-011's Session
//! lifecycle: every Session is a PROV-O `Activity` carrying its feature
//! id, bundle/model refs, started/ended-at timestamps, optional status,
//! and output ref (ADR-004). `list` paginates Sessions by start time;
//! `log` walks the PROV-O chain of a single Session — bundle/model used,
//! Dispatch derived from the Session, and downstream `CodeChange` when
//! present.
//!
//! Both helpers refuse cleanly when the working dir has no `.dec/`
//! (ADR-012). They never mutate the store.

use std::path::Path;

use anyhow::{anyhow, Context, Result};
use oxigraph::io::RdfFormat;
use oxigraph::sparql::QueryResults;
use oxigraph::store::Store;

const DEC_NS: &str = "https://decision-cli.dev/ns#";
const PROV_NS: &str = "http://www.w3.org/ns/prov#";

/// One row of `dec session list` output.
#[derive(Debug, Clone)]
pub struct SessionSummary {
    /// Session IRI.
    pub iri: String,
    /// `dec:featureId` literal (feature this Session targets).
    pub feature_id: String,
    /// RFC-3339 `prov:atTime`. Empty if missing.
    pub started_at: String,
    /// `dec:status` if recorded. Empty if pending.
    pub status: String,
}

/// PROV-O chain for one Session, surfaced by `dec session log`.
#[derive(Debug, Clone, Default)]
pub struct SessionLog {
    /// Session IRI being inspected.
    pub session_iri: String,
    /// `dec:featureId` literal.
    pub feature_id: String,
    /// RFC-3339 start / end timestamps. End may be empty.
    pub started_at: String,
    /// RFC-3339 end timestamp. Empty when still in flight.
    pub ended_at: String,
    /// `dec:status` literal. Empty when pending.
    pub status: String,
    /// IRI of the active `ValueStream` (from `dec:inStream`).
    pub stream_iri: String,
    /// IRI of the bundle reference plus its content hash.
    pub bundle_ref: String,
    /// SHA-256 content hash of the bundle.
    pub bundle_hash: String,
    /// IRI of the model reference plus its model version literal.
    pub model_ref: String,
    /// Model version literal.
    pub model_version: String,
    /// Dispatch IRI generated by the Session (PROV-O `wasGeneratedBy`).
    pub dispatch_iri: String,
    /// Output ref recorded on the Session (`CodeChange` IRI). Empty when
    /// the session has not yet completed.
    pub output_ref: String,
}

/// List recent Sessions, oldest first by `prov:atTime`. `limit` caps the
/// number of rows returned; `offset` skips that many rows from the
/// **top** of the ascending-ordered list (slice 1 keeps pagination
/// simple — for "show me the latest N" callers can sort client-side).
pub fn list(workdir: &Path, limit: usize, offset: usize) -> Result<Vec<SessionSummary>> {
    let store = open_store(workdir)?;
    let q = build_session_list_query(limit, offset);
    let results = store.query(q.as_str()).context("session-list SPARQL")?;
    let QueryResults::Solutions(sols) = results else {
        return Err(anyhow!("session-list: unexpected SPARQL result shape"));
    };
    let mut out = Vec::new();
    for sol in sols {
        let sol = sol.context("session-list SPARQL row")?;
        out.push(decode_session_summary_row(&sol));
    }
    Ok(out)
}

/// Build the SPARQL `SELECT` used by [`list`]. `ORDER BY ?started` keeps
/// results stable; `OPTIONAL` on feature/status preserves rows for
/// sessions not yet tagged. Numeric LIMIT/OFFSET are interpolated since
/// SPARQL has no portable numeric bind.
fn build_session_list_query(limit: usize, offset: usize) -> String {
    format!(
        "PREFIX dec: <{DEC_NS}>
PREFIX prov: <{PROV_NS}>
SELECT ?session ?feature ?started ?status WHERE {{
  GRAPH ?g {{
    ?session a dec:Session .
    OPTIONAL {{ ?session prov:atTime ?started }}
    OPTIONAL {{ ?session dec:featureId ?feature }}
    OPTIONAL {{ ?session dec:status ?status }}
  }}
}} ORDER BY ?started LIMIT {limit} OFFSET {offset}"
    )
}

/// Decode one `list` solution row into a [`SessionSummary`].
fn decode_session_summary_row(sol: &oxigraph::sparql::QuerySolution) -> SessionSummary {
    let iri = sol
        .get("session")
        .map_or_else(|| "(unknown)".into(), term_iri);
    let feature_id = sol.get("feature").map(term_literal).unwrap_or_default();
    let started_at = sol.get("started").map(term_literal).unwrap_or_default();
    let status = sol.get("status").map(term_literal).unwrap_or_default();
    SessionSummary {
        iri,
        feature_id,
        started_at,
        status,
    }
}

/// Walk the PROV-O chain anchored on `session_iri`.
///
/// Returns `Err` when the Session does not exist in the store — the
/// `Result` shape lets the caller decide between exit codes 1 and 64.
pub fn log(workdir: &Path, session_iri: &str) -> Result<SessionLog> {
    let store = open_store(workdir)?;
    let mut log = SessionLog {
        session_iri: session_iri.to_string(),
        ..SessionLog::default()
    };
    populate_core_fields(&store, session_iri, &mut log)?;
    populate_dispatch(&store, session_iri, &mut log)?;
    Ok(log)
}

/// Phase 1 of [`log`]: load the Session row's own fields (feature,
/// timestamps, status, stream, bundle/model refs, output) into `log`.
/// Errors with a clear message when the Session is absent.
fn populate_core_fields(store: &Store, session_iri: &str, log: &mut SessionLog) -> Result<()> {
    let core_q = build_core_query(session_iri);
    let results = store
        .query(core_q.as_str())
        .context("session-log core SPARQL")?;
    let QueryResults::Solutions(mut sols) = results else {
        return Err(anyhow!("session-log: unexpected SPARQL result shape"));
    };
    let Some(sol_res) = sols.next() else {
        return Err(anyhow!(
            "no Session with IRI <{session_iri}> in the orchestration store"
        ));
    };
    let sol = sol_res.context("session-log SPARQL row")?;
    decode_core_fields(&sol, log);
    Ok(())
}

/// Phase 2 of [`log`]: record the IRI of the Dispatch generated by this
/// Session. Quietly leaves `dispatch_iri` empty when none exists.
fn populate_dispatch(store: &Store, session_iri: &str, log: &mut SessionLog) -> Result<()> {
    let dispatch_q = format!(
        "PREFIX dec: <{DEC_NS}>
PREFIX prov: <{PROV_NS}>
SELECT ?dispatch WHERE {{
  GRAPH ?g {{
    ?dispatch a dec:Dispatch ;
              prov:wasGeneratedBy <{session_iri}> .
  }}
}} LIMIT 1"
    );
    let results = store
        .query(dispatch_q.as_str())
        .context("session-log dispatch SPARQL")?;
    if let QueryResults::Solutions(mut sols) = results {
        if let Some(sol_res) = sols.next() {
            let sol = sol_res.context("session-log dispatch row")?;
            log.dispatch_iri = sol.get("dispatch").map(term_iri).unwrap_or_default();
        }
    }
    Ok(())
}

/// Build the Phase 1 SPARQL `SELECT` for [`populate_core_fields`].
fn build_core_query(session_iri: &str) -> String {
    format!(
        "PREFIX dec: <{DEC_NS}>
PREFIX prov: <{PROV_NS}>
SELECT ?feature ?started ?ended ?status ?stream ?bundleRef ?bundleHash ?modelRef ?modelVersion ?output WHERE {{
  GRAPH ?g {{
    <{session_iri}> a dec:Session ;
                    dec:inStream ?stream ;
                    prov:used ?bundleRef ;
                    prov:used ?modelRef .
    OPTIONAL {{ ?bundleRef dec:contentHash ?bundleHash }}
    OPTIONAL {{ ?modelRef dec:modelVersion ?modelVersion }}
    OPTIONAL {{ <{session_iri}> dec:featureId ?feature }}
    OPTIONAL {{ <{session_iri}> prov:atTime ?started }}
    OPTIONAL {{ <{session_iri}> prov:endedAtTime ?ended }}
    OPTIONAL {{ <{session_iri}> dec:status ?status }}
    OPTIONAL {{ <{session_iri}> dec:outputRef ?output }}
  }}
}} LIMIT 1"
    )
}

/// Copy the Phase 1 SPARQL solution into the mutable [`SessionLog`].
fn decode_core_fields(sol: &oxigraph::sparql::QuerySolution, log: &mut SessionLog) {
    log.feature_id = sol.get("feature").map(term_literal).unwrap_or_default();
    log.started_at = sol.get("started").map(term_literal).unwrap_or_default();
    log.ended_at = sol.get("ended").map(term_literal).unwrap_or_default();
    log.status = sol.get("status").map(term_literal).unwrap_or_default();
    log.stream_iri = sol.get("stream").map(term_iri).unwrap_or_default();
    log.bundle_ref = sol.get("bundleRef").map(term_iri).unwrap_or_default();
    log.bundle_hash = sol.get("bundleHash").map(term_literal).unwrap_or_default();
    log.model_ref = sol.get("modelRef").map(term_iri).unwrap_or_default();
    log.model_version = sol
        .get("modelVersion")
        .map(term_literal)
        .unwrap_or_default();
    log.output_ref = sol.get("output").map(term_iri).unwrap_or_default();
}

/// Format [`SessionLog`] for human-readable terminal output (slice 1).
/// JSON output is deferred per FT-012's scope.
#[must_use]
pub fn format_log(log: &SessionLog) -> String {
    let blank = |s: &str| if s.is_empty() { "(none)" } else { s }.to_string();
    let status = render_status(&log.status);
    format!(
        "Session: {iri}\n  \
         Feature:        {feature}\n  \
         Stream:         {stream}\n  \
         Started:        {started}\n  \
         Ended:          {ended}\n  \
         Status:         {status}\n  \
         Bundle ref:     {bref}\n  \
         Bundle hash:    {bhash}\n  \
         Model ref:      {mref}\n  \
         Model version:  {mver}\n  \
         Dispatch:       {disp}\n  \
         Output:         {out}\n",
        iri = log.session_iri,
        feature = blank(&log.feature_id),
        stream = blank(&log.stream_iri),
        started = blank(&log.started_at),
        ended = blank(&log.ended_at),
        bref = blank(&log.bundle_ref),
        bhash = blank(&log.bundle_hash),
        mref = blank(&log.model_ref),
        mver = blank(&log.model_version),
        disp = blank(&log.dispatch_iri),
        out = blank(&log.output_ref),
    )
}

/// Render the Session `dec:status` literal for the `format_log` output;
/// substitute the explicit `(pending)` placeholder when the field is
/// empty so consumers can tell pending apart from missing.
fn render_status(status: &str) -> String {
    if status.is_empty() {
        "(pending)".to_string()
    } else {
        status.to_string()
    }
}

fn open_store(workdir: &Path) -> Result<Store> {
    let dump_path = workdir.join(".dec").join("store").join("orchestration.nq");
    if !dump_path.exists() {
        return Err(anyhow!(
            "no orchestration store at {} — run `dec init` first",
            dump_path.display()
        ));
    }
    let bytes =
        std::fs::read(&dump_path).with_context(|| format!("reading {}", dump_path.display()))?;
    let store = Store::new().context("opening in-memory orchestration store")?;
    store
        .load_from_reader(RdfFormat::NQuads, bytes.as_slice())
        .with_context(|| format!("loading {}", dump_path.display()))?;
    Ok(store)
}

fn term_iri(t: &oxigraph::model::Term) -> String {
    match t {
        oxigraph::model::Term::NamedNode(n) => n.as_str().to_string(),
        other => other.to_string(),
    }
}

fn term_literal(t: &oxigraph::model::Term) -> String {
    match t {
        oxigraph::model::Term::Literal(lit) => lit.value().to_string(),
        oxigraph::model::Term::NamedNode(n) => n.as_str().to_string(),
        other => other.to_string(),
    }
}
