// Mechanical cell: add-artifact-type/iri_module_consts
// Generated by cluster_dispatch as a deterministic template.
// Derives from:
//   - rust_struct (7096 bytes)
// Registration / help-doc placeholder — wire-up code.
