"""Bundle layer — read-only accessors for artifacts dispatched in a bundle.

The typed accessors under :mod:`pipeline_worker_sdk.bundle._generated` are
generated by the FT-085 codegen pipeline from the SHACL shapes shipped at
``workers/_shared/shapes/``. Workers consume them through the hand-written
:class:`Bundle` facade (FT-079); the harness side packs the same shapes,
so there is no semantic drift between producer and consumer (ADR-048).
"""

from . import _generated as accessors  # noqa: F401  re-exported for callers
from ._facade import (
    ADR_TYPE_IRI,
    DEC_NS,
    TC_TYPE_IRI,
    Bundle,
    UnknownFocalTypeError,
)

__all__ = [
    "ADR_TYPE_IRI",
    "Bundle",
    "DEC_NS",
    "TC_TYPE_IRI",
    "UnknownFocalTypeError",
    "accessors",
]
