"""Bundle layer — read-only accessors for artifacts dispatched in a bundle.

The typed accessors under :mod:`pipeline_worker_sdk.bundle._generated` are
generated by the FT-085 codegen pipeline from the SHACL shapes shipped at
``workers/_shared/shapes/``. Workers consume them to read bundle contents
with full IDE / mypy support; the harness side packs the same shapes, so
there is no semantic drift between producer and consumer (ADR-048).
"""

from . import _generated as accessors  # noqa: F401  re-exported for callers

__all__ = ["accessors"]
