"""Artifact layer — typed builders for emitting artifact triples.

The typed builders under :mod:`pipeline_worker_sdk.artifact._generated` are
generated by the FT-085 codegen pipeline from the SHACL shapes shipped at
``workers/_shared/shapes/``. Workers compose them; the harness re-validates
authoritatively at the GraphWriter chokepoint (ADR-041).
"""

from . import _generated as builders  # noqa: F401

__all__ = ["builders"]
