"""Artifact layer — typed builders for emitting artifact triples.

The typed builders under :mod:`pipeline_worker_sdk.artifact._generated` are
generated by the FT-085 codegen pipeline from the SHACL shapes shipped at
``workers/_shared/shapes/``. They extend :class:`BuilderBase` (FT-080) for
the shared ``commit()`` / ``emit_triple`` / ``link_to`` /
``mark_boundary_artifact`` surface; SHACL-derived validation runs locally
on ``commit()`` and the harness re-validates authoritatively at the
GraphWriter chokepoint (ADR-041 / FT-073).
"""

from . import _generated as builders  # noqa: F401
from ._base import (
    DEC_BOUNDARY_ARTIFACT,
    DEC_EXTERNAL_ORIGIN,
    DEC_NS,
    RDF_TYPE_IRI,
    BuilderBase,
    CommitError,
    MotivationalDescriptor,
)

__all__ = [
    "DEC_BOUNDARY_ARTIFACT",
    "DEC_EXTERNAL_ORIGIN",
    "DEC_NS",
    "RDF_TYPE_IRI",
    "BuilderBase",
    "CommitError",
    "MotivationalDescriptor",
    "builders",
]
