// Mechanical cell: add-cli-subcommand/help_doc_string
// Generated by cluster_dispatch as a deterministic template.
// Derives from:
//   - clap_args_module (502 bytes)
// Registration / help-doc placeholder — wire-up code.
