// Mechanical cell: add-cli-subcommand/registration_wiring
// Generated by cluster_dispatch as a deterministic template.
// Derives from:
//   - clap_args_module (502 bytes)
//   - handler_module (470 bytes)
// Registration / help-doc placeholder — wire-up code.
